yarnPath: .yarn/releases/yarn-3.6.0.cjs
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
# Required by Angular ng build
nodeLinker: node-modules